version: '3.7'
services:
  chatbot:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    environment:
      - HOST_DATA_DIR=/app/data
      - SECRET_KEY=${SECRET_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    volumes:
      - ./data:/app/data
      - ./.config.yml:/app/.config.yml
      - ./.env:/app/.env
